### PR TITLE
Fix OAuth routes to Lumen 5.7

### PR DESCRIPTION
**Pull request by lucascardial**

### CODE REVIEW

**Comment by lucascardial** [comment]
Hello @kayrules .
When will you post this update to packagist?

**Comment by kayrules** [comment]
Hi @lucca-cardial, thanks for the PR. already updated the packagist pointing to v0.3.0

**Comment by lucascardial** [comment]
Do you think to update the dependency of @moeen-basra/laravel-passport-mongodb? This project is using version 1.0.18, where the `makeAuthorizationServer` method in PassportServiceProvider is not setting the` EncryptionKey`.
I tried to run some tests with version 4.0 @moeen-basra/laravel-passport-mongodb, but many errors occurred.

**Comment by lucascardial** [comment]
I made a modification to the vendor of MoeenBasra \ LaravelPassportMongoDB \ PassportServiceProvider :: makeAuthorizationServer (line 196):
````
public function makeAuthorizationServer()
    {
        $authorizationServer = new AuthorizationServer(
            $this->app->make(Bridge\ClientRepository::class),
            $this->app->make(Bridge\AccessTokenRepository::class),
            $this->app->make(Bridge\ScopeRepository::class),
            'file://'.Passport::keyPath('oauth-private.key'),
            'file://'.Passport::keyPath('oauth-public.key')
        );

        $authorizationServer->setEncryptionKey(env('APP_KEY'));

        return $authorizationServer;
    }
````

**Comment by lucascardial** [comment]
With this modification, I can generate passport tokens normally. The problem is that I can not test version 4.0 that already fixes this. Other errors arise.
I'm thinking of cloning only version 1.0.18 and uploaded it to my repository and packagist.

**Pull request merged**
